version: '3.9'
services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5054:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgamdin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres

  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_SERVER_PROXY_URI: https://api.openweathermap.org/data/2.5/weather?q=London,uk&appid=API_KEY
    depends_on:
      - postgres
